// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Peppol.Ademico.Kiota.Api.Peppol.V1.InvoiceResponses;
using Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices;
using Peppol.Ademico.Kiota.Api.Peppol.V1.LegalEntities;
using Peppol.Ademico.Kiota.Api.Peppol.V1.Notifications;
using Peppol.Ademico.Kiota.Api.Peppol.V1.Tools;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Peppol.Ademico.Kiota.Api.Peppol.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \api\peppol\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The invoiceResponses property</summary>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.InvoiceResponses.InvoiceResponsesRequestBuilder InvoiceResponses
        {
            get => new global::Peppol.Ademico.Kiota.Api.Peppol.V1.InvoiceResponses.InvoiceResponsesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invoices property</summary>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.InvoicesRequestBuilder Invoices
        {
            get => new global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.InvoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The legalEntities property</summary>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.LegalEntities.LegalEntitiesRequestBuilder LegalEntities
        {
            get => new global::Peppol.Ademico.Kiota.Api.Peppol.V1.LegalEntities.LegalEntitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The notifications property</summary>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.Notifications.NotificationsRequestBuilder Notifications
        {
            get => new global::Peppol.Ademico.Kiota.Api.Peppol.V1.Notifications.NotificationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tools property</summary>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.Tools.ToolsRequestBuilder Tools
        {
            get => new global::Peppol.Ademico.Kiota.Api.Peppol.V1.Tools.ToolsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/peppol/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/peppol/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
