// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item;
using Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.UblSubmissions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices
{
    /// <summary>
    /// Builds and executes requests for operations under \api\peppol\v1\invoices
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvoicesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ublSubmissions property</summary>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.UblSubmissions.UblSubmissionsRequestBuilder UblSubmissions
        {
            get => new global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.UblSubmissions.UblSubmissionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Peppol.Ademico.Kiota.api.peppol.v1.invoices.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item.WithTransmissionItemRequestBuilder"/></returns>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item.WithTransmissionItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("transmissionId", position);
                return new global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item.WithTransmissionItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.InvoicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvoicesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/peppol/v1/invoices", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.InvoicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InvoicesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/peppol/v1/invoices", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
