// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item.Ubl;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\peppol\v1\invoices\{transmissionId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTransmissionItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ubl property</summary>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item.Ubl.UblRequestBuilder Ubl
        {
            get => new global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item.Ubl.UblRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item.WithTransmissionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTransmissionItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/peppol/v1/invoices/{transmissionId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.Invoices.Item.WithTransmissionItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTransmissionItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/peppol/v1/invoices/{transmissionId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
