// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Peppol.Ademico.Kiota.Api.Peppol.V1.Tools.Connectivity;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Peppol.Ademico.Kiota.Api.Peppol.V1.Tools
{
    /// <summary>
    /// Builds and executes requests for operations under \api\peppol\v1\tools
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ToolsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The connectivity property</summary>
        public global::Peppol.Ademico.Kiota.Api.Peppol.V1.Tools.Connectivity.ConnectivityRequestBuilder Connectivity
        {
            get => new global::Peppol.Ademico.Kiota.Api.Peppol.V1.Tools.Connectivity.ConnectivityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.Tools.ToolsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToolsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/peppol/v1/tools", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Api.Peppol.V1.Tools.ToolsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ToolsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/peppol/v1/tools", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
