// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum C5SubmissionResultRO_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "SCHEDULED")]
        #pragma warning disable CS1591
        SCHEDULED,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOT_SENDING")]
        #pragma warning disable CS1591
        NOT_SENDING,
        #pragma warning restore CS1591
    }
}
