// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>Clarification code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClarificationCodeEnum
    {
        [EnumMember(Value = "NON")]
        #pragma warning disable CS1591
        NON,
        #pragma warning restore CS1591
        [EnumMember(Value = "REF")]
        #pragma warning disable CS1591
        REF,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEG")]
        #pragma warning disable CS1591
        LEG,
        #pragma warning restore CS1591
        [EnumMember(Value = "REC")]
        #pragma warning disable CS1591
        REC,
        #pragma warning restore CS1591
        [EnumMember(Value = "QUA")]
        #pragma warning disable CS1591
        QUA,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEL")]
        #pragma warning disable CS1591
        DEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "PRI")]
        #pragma warning disable CS1591
        PRI,
        #pragma warning restore CS1591
        [EnumMember(Value = "QTY")]
        #pragma warning disable CS1591
        QTY,
        #pragma warning restore CS1591
        [EnumMember(Value = "ITM")]
        #pragma warning disable CS1591
        ITM,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAY")]
        #pragma warning disable CS1591
        PAY,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNR")]
        #pragma warning disable CS1591
        UNR,
        #pragma warning restore CS1591
        [EnumMember(Value = "FIN")]
        #pragma warning disable CS1591
        FIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "PPD")]
        #pragma warning disable CS1591
        PPD,
        #pragma warning restore CS1591
        [EnumMember(Value = "NOA")]
        #pragma warning disable CS1591
        NOA,
        #pragma warning restore CS1591
        [EnumMember(Value = "PIN")]
        #pragma warning disable CS1591
        PIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "NIN")]
        #pragma warning disable CS1591
        NIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNF")]
        #pragma warning disable CS1591
        CNF,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNP")]
        #pragma warning disable CS1591
        CNP,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNA")]
        #pragma warning disable CS1591
        CNA,
        #pragma warning restore CS1591
        [EnumMember(Value = "OTH")]
        #pragma warning disable CS1591
        OTH,
        #pragma warning restore CS1591
    }
}
