// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>Clarification type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClarificationTypeEnum
    {
        [EnumMember(Value = "OPStatusReason")]
        #pragma warning disable CS1591
        OPStatusReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "OPStatusAction")]
        #pragma warning disable CS1591
        OPStatusAction,
        #pragma warning restore CS1591
    }
}
