// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>
    /// Contains the transmission details(eg transmissionId) that can be used later on to identify the document transmission
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DocumentSubmissionResult : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The C5 submission result if C5 is activated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.C5SubmissionResultRO? C5SubmissionResult { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.C5SubmissionResultRO C5SubmissionResult { get; set; }
#endif
        /// <summary>The document id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DocumentId { get; set; }
#nullable restore
#else
        public string DocumentId { get; set; }
#endif
        /// <summary>The document type</summary>
        public global::Peppol.Ademico.Kiota.Models.PeppolDocumentTypeEnum? DocumentTypeEnum { get; set; }
        /// <summary>The receiver of the document eg the Buyer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Receiver { get; set; }
#nullable restore
#else
        public string Receiver { get; set; }
#endif
        /// <summary>The SBDH instance identifier used when sending the document</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SbdhInstanceIdentifier { get; set; }
#nullable restore
#else
        public string SbdhInstanceIdentifier { get; set; }
#endif
        /// <summary>The sender of the document eg the Seller</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sender { get; set; }
#nullable restore
#else
        public string Sender { get; set; }
#endif
        /// <summary>Document transmission id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransmissionId { get; set; }
#nullable restore
#else
        public string TransmissionId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Models.DocumentSubmissionResult"/> and sets the default values.
        /// </summary>
        public DocumentSubmissionResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Peppol.Ademico.Kiota.Models.DocumentSubmissionResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Peppol.Ademico.Kiota.Models.DocumentSubmissionResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Peppol.Ademico.Kiota.Models.DocumentSubmissionResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "c5SubmissionResult", n => { C5SubmissionResult = n.GetObjectValue<global::Peppol.Ademico.Kiota.Models.C5SubmissionResultRO>(global::Peppol.Ademico.Kiota.Models.C5SubmissionResultRO.CreateFromDiscriminatorValue); } },
                { "documentId", n => { DocumentId = n.GetStringValue(); } },
                { "documentTypeEnum", n => { DocumentTypeEnum = n.GetEnumValue<global::Peppol.Ademico.Kiota.Models.PeppolDocumentTypeEnum>(); } },
                { "receiver", n => { Receiver = n.GetStringValue(); } },
                { "sbdhInstanceIdentifier", n => { SbdhInstanceIdentifier = n.GetStringValue(); } },
                { "sender", n => { Sender = n.GetStringValue(); } },
                { "transmissionId", n => { TransmissionId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.C5SubmissionResultRO>("c5SubmissionResult", C5SubmissionResult);
            writer.WriteStringValue("documentId", DocumentId);
            writer.WriteEnumValue<global::Peppol.Ademico.Kiota.Models.PeppolDocumentTypeEnum>("documentTypeEnum", DocumentTypeEnum);
            writer.WriteStringValue("receiver", Receiver);
            writer.WriteStringValue("sbdhInstanceIdentifier", SbdhInstanceIdentifier);
            writer.WriteStringValue("sender", Sender);
            writer.WriteStringValue("transmissionId", TransmissionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
