// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>The status of the Invoice/Credit Note for which we have sent an Invoice Response</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DocumentStatusEnumRO
    {
        [EnumMember(Value = "QUEUED")]
        #pragma warning disable CS1591
        QUEUED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SENT")]
        #pragma warning disable CS1591
        SENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEND_FAILED")]
        #pragma warning disable CS1591
        SEND_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TECHNICAL_ACCEPTANCE")]
        #pragma warning disable CS1591
        TECHNICAL_ACCEPTANCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUYER_ACKNOWLEDGE")]
        #pragma warning disable CS1591
        BUYER_ACKNOWLEDGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PROCESS")]
        #pragma warning disable CS1591
        IN_PROCESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "UNDER_QUERY")]
        #pragma warning disable CS1591
        UNDER_QUERY,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONDITIONALLY_ACCEPTED")]
        #pragma warning disable CS1591
        CONDITIONALLY_ACCEPTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        REJECTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPTED")]
        #pragma warning disable CS1591
        ACCEPTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIALLY_PAID")]
        #pragma warning disable CS1591
        PARTIALLY_PAID,
        #pragma warning restore CS1591
        [EnumMember(Value = "FULLY_PAID")]
        #pragma warning disable CS1591
        FULLY_PAID,
        #pragma warning restore CS1591
    }
}
