// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>The event type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventTypeRO
    {
        [EnumMember(Value = "DOCUMENT_SENT")]
        #pragma warning disable CS1591
        DOCUMENT_SENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_SEND_FAILED")]
        #pragma warning disable CS1591
        DOCUMENT_SEND_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MLR_RECEIVED")]
        #pragma warning disable CS1591
        MLR_RECEIVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVOICE_RESPONSE_RECEIVED")]
        #pragma warning disable CS1591
        INVOICE_RESPONSE_RECEIVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DOCUMENT_RECEIVED")]
        #pragma warning disable CS1591
        DOCUMENT_RECEIVED,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVOICE_RESPONSE_SENT")]
        #pragma warning disable CS1591
        INVOICE_RESPONSE_SENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVOICE_RESPONSE_SEND_FAILED")]
        #pragma warning disable CS1591
        INVOICE_RESPONSE_SEND_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL_ENTITY_KYC_CORPPASS_ACTIVATED")]
        #pragma warning disable CS1591
        LEGAL_ENTITY_KYC_CORPPASS_ACTIVATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL_ENTITY_KYC_CORPPASS_ACTIVATION_ERROR")]
        #pragma warning disable CS1591
        LEGAL_ENTITY_KYC_CORPPASS_ACTIVATION_ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL_ENTITY_C5_ACTIVATED")]
        #pragma warning disable CS1591
        LEGAL_ENTITY_C5_ACTIVATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL_ENTITY_C5_ACTIVATION_ERROR")]
        #pragma warning disable CS1591
        LEGAL_ENTITY_C5_ACTIVATION_ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL_ENTITY_C5_DEACTIVATED")]
        #pragma warning disable CS1591
        LEGAL_ENTITY_C5_DEACTIVATED,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL_ENTITY_C5_DEACTIVATION_ERROR")]
        #pragma warning disable CS1591
        LEGAL_ENTITY_C5_DEACTIVATION_ERROR,
        #pragma warning restore CS1591
        [EnumMember(Value = "IRAS_DOCUMENT_SENT")]
        #pragma warning disable CS1591
        IRAS_DOCUMENT_SENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "IRAS_DOCUMENT_SEND_FAILED")]
        #pragma warning disable CS1591
        IRAS_DOCUMENT_SEND_FAILED,
        #pragma warning restore CS1591
    }
}
