// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>
    /// Clarification to state the Buyer&apos;s reason for the status and/or any expected action from the Seller&apos;s side
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InvoiceClarificationRO : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Clarification description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Clarification { get; set; }
#nullable restore
#else
        public string Clarification { get; set; }
#endif
        /// <summary>Clarification code</summary>
        public global::Peppol.Ademico.Kiota.Models.ClarificationCodeEnum? ClarificationCode { get; set; }
        /// <summary>Clarification type</summary>
        public global::Peppol.Ademico.Kiota.Models.ClarificationTypeEnum? ClarificationType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceClarificationRO"/> and sets the default values.
        /// </summary>
        public InvoiceClarificationRO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceClarificationRO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Peppol.Ademico.Kiota.Models.InvoiceClarificationRO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Peppol.Ademico.Kiota.Models.InvoiceClarificationRO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "clarification", n => { Clarification = n.GetStringValue(); } },
                { "clarificationCode", n => { ClarificationCode = n.GetEnumValue<global::Peppol.Ademico.Kiota.Models.ClarificationCodeEnum>(); } },
                { "clarificationType", n => { ClarificationType = n.GetEnumValue<global::Peppol.Ademico.Kiota.Models.ClarificationTypeEnum>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("clarification", Clarification);
            writer.WriteEnumValue<global::Peppol.Ademico.Kiota.Models.ClarificationCodeEnum>("clarificationCode", ClarificationCode);
            writer.WriteEnumValue<global::Peppol.Ademico.Kiota.Models.ClarificationTypeEnum>("clarificationType", ClarificationType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
