// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>The Invoice Response status code</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InvoiceResponseCodeEnumRO
    {
        [EnumMember(Value = "AB")]
        #pragma warning disable CS1591
        AB,
        #pragma warning restore CS1591
        [EnumMember(Value = "IP")]
        #pragma warning disable CS1591
        IP,
        #pragma warning restore CS1591
        [EnumMember(Value = "UQ")]
        #pragma warning disable CS1591
        UQ,
        #pragma warning restore CS1591
        [EnumMember(Value = "CA")]
        #pragma warning disable CS1591
        CA,
        #pragma warning restore CS1591
        [EnumMember(Value = "RE")]
        #pragma warning disable CS1591
        RE,
        #pragma warning restore CS1591
        [EnumMember(Value = "AP")]
        #pragma warning disable CS1591
        AP,
        #pragma warning restore CS1591
        [EnumMember(Value = "PD")]
        #pragma warning disable CS1591
        PD,
        #pragma warning restore CS1591
    }
}
