// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>
    /// The details of the legal entity which is registered in the Peppol network
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LegalEntityRO : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The details of the legal entity which is registered in the Peppol network</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.LegalEntityDetailsRO? LegalEntityDetails { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.LegalEntityDetailsRO LegalEntityDetails { get; set; }
#endif
        /// <summary>The legal entity id</summary>
        public long? LegalEntityId { get; set; }
        /// <summary>The registrations of the legal entity in the Peppol network. A registration contains the Peppol identifier and the legal entity supported documents. &lt;/br&gt;A legal entity can be registered multiple times using different identifiers eg company registration number, VAT, etc</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Peppol.Ademico.Kiota.Models.LegalEntityPeppolRegistrationRO>? PeppolRegistrations { get; set; }
#nullable restore
#else
        public List<global::Peppol.Ademico.Kiota.Models.LegalEntityPeppolRegistrationRO> PeppolRegistrations { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Models.LegalEntityRO"/> and sets the default values.
        /// </summary>
        public LegalEntityRO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Peppol.Ademico.Kiota.Models.LegalEntityRO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Peppol.Ademico.Kiota.Models.LegalEntityRO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Peppol.Ademico.Kiota.Models.LegalEntityRO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "legalEntityDetails", n => { LegalEntityDetails = n.GetObjectValue<global::Peppol.Ademico.Kiota.Models.LegalEntityDetailsRO>(global::Peppol.Ademico.Kiota.Models.LegalEntityDetailsRO.CreateFromDiscriminatorValue); } },
                { "legalEntityId", n => { LegalEntityId = n.GetLongValue(); } },
                { "peppolRegistrations", n => { PeppolRegistrations = n.GetCollectionOfObjectValues<global::Peppol.Ademico.Kiota.Models.LegalEntityPeppolRegistrationRO>(global::Peppol.Ademico.Kiota.Models.LegalEntityPeppolRegistrationRO.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.LegalEntityDetailsRO>("legalEntityDetails", LegalEntityDetails);
            writer.WriteLongValue("legalEntityId", LegalEntityId);
            writer.WriteCollectionOfObjectValues<global::Peppol.Ademico.Kiota.Models.LegalEntityPeppolRegistrationRO>("peppolRegistrations", PeppolRegistrations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
