// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceReceivingNotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceResponseReceivingNotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceResponseSendingNotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceSendingNotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.IrasSendingNotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassC5NotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassKycNotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.MLRReceivingNotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.OrderReceivingNotificationRO"/>, <see cref="global::Peppol.Ademico.Kiota.Models.OrderSendingNotificationRO"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NotificationRO : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceReceivingNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.InvoiceReceivingNotificationRO? InvoiceReceivingNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.InvoiceReceivingNotificationRO InvoiceReceivingNotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceResponseReceivingNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.InvoiceResponseReceivingNotificationRO? InvoiceResponseReceivingNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.InvoiceResponseReceivingNotificationRO InvoiceResponseReceivingNotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceResponseSendingNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.InvoiceResponseSendingNotificationRO? InvoiceResponseSendingNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.InvoiceResponseSendingNotificationRO InvoiceResponseSendingNotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.InvoiceSendingNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.InvoiceSendingNotificationRO? InvoiceSendingNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.InvoiceSendingNotificationRO InvoiceSendingNotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.IrasSendingNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.IrasSendingNotificationRO? IrasSendingNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.IrasSendingNotificationRO IrasSendingNotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassC5NotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassC5NotificationRO? LegalEntityCorppassC5NotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassC5NotificationRO LegalEntityCorppassC5NotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassKycNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassKycNotificationRO? LegalEntityCorppassKycNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassKycNotificationRO LegalEntityCorppassKycNotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.MLRReceivingNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.MLRReceivingNotificationRO? MLRReceivingNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.MLRReceivingNotificationRO MLRReceivingNotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.OrderReceivingNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.OrderReceivingNotificationRO? OrderReceivingNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.OrderReceivingNotificationRO OrderReceivingNotificationRO { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Peppol.Ademico.Kiota.Models.OrderSendingNotificationRO"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Peppol.Ademico.Kiota.Models.OrderSendingNotificationRO? OrderSendingNotificationRO { get; set; }
#nullable restore
#else
        public global::Peppol.Ademico.Kiota.Models.OrderSendingNotificationRO OrderSendingNotificationRO { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Peppol.Ademico.Kiota.Models.NotificationRO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Peppol.Ademico.Kiota.Models.NotificationRO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Peppol.Ademico.Kiota.Models.NotificationRO();
            if("InvoiceReceivingNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InvoiceReceivingNotificationRO = new global::Peppol.Ademico.Kiota.Models.InvoiceReceivingNotificationRO();
            }
            else if("InvoiceResponseReceivingNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InvoiceResponseReceivingNotificationRO = new global::Peppol.Ademico.Kiota.Models.InvoiceResponseReceivingNotificationRO();
            }
            else if("InvoiceResponseSendingNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InvoiceResponseSendingNotificationRO = new global::Peppol.Ademico.Kiota.Models.InvoiceResponseSendingNotificationRO();
            }
            else if("InvoiceSendingNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InvoiceSendingNotificationRO = new global::Peppol.Ademico.Kiota.Models.InvoiceSendingNotificationRO();
            }
            else if("IrasSendingNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.IrasSendingNotificationRO = new global::Peppol.Ademico.Kiota.Models.IrasSendingNotificationRO();
            }
            else if("LegalEntityCorppassC5NotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LegalEntityCorppassC5NotificationRO = new global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassC5NotificationRO();
            }
            else if("LegalEntityCorppassKycNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LegalEntityCorppassKycNotificationRO = new global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassKycNotificationRO();
            }
            else if("MLRReceivingNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MLRReceivingNotificationRO = new global::Peppol.Ademico.Kiota.Models.MLRReceivingNotificationRO();
            }
            else if("OrderReceivingNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.OrderReceivingNotificationRO = new global::Peppol.Ademico.Kiota.Models.OrderReceivingNotificationRO();
            }
            else if("OrderSendingNotificationRO".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.OrderSendingNotificationRO = new global::Peppol.Ademico.Kiota.Models.OrderSendingNotificationRO();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(InvoiceReceivingNotificationRO != null)
            {
                return InvoiceReceivingNotificationRO.GetFieldDeserializers();
            }
            else if(InvoiceResponseReceivingNotificationRO != null)
            {
                return InvoiceResponseReceivingNotificationRO.GetFieldDeserializers();
            }
            else if(InvoiceResponseSendingNotificationRO != null)
            {
                return InvoiceResponseSendingNotificationRO.GetFieldDeserializers();
            }
            else if(InvoiceSendingNotificationRO != null)
            {
                return InvoiceSendingNotificationRO.GetFieldDeserializers();
            }
            else if(IrasSendingNotificationRO != null)
            {
                return IrasSendingNotificationRO.GetFieldDeserializers();
            }
            else if(LegalEntityCorppassC5NotificationRO != null)
            {
                return LegalEntityCorppassC5NotificationRO.GetFieldDeserializers();
            }
            else if(LegalEntityCorppassKycNotificationRO != null)
            {
                return LegalEntityCorppassKycNotificationRO.GetFieldDeserializers();
            }
            else if(MLRReceivingNotificationRO != null)
            {
                return MLRReceivingNotificationRO.GetFieldDeserializers();
            }
            else if(OrderReceivingNotificationRO != null)
            {
                return OrderReceivingNotificationRO.GetFieldDeserializers();
            }
            else if(OrderSendingNotificationRO != null)
            {
                return OrderSendingNotificationRO.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            if(InvoiceReceivingNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.InvoiceReceivingNotificationRO>(null, InvoiceReceivingNotificationRO);
            }
            else if(InvoiceResponseReceivingNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.InvoiceResponseReceivingNotificationRO>(null, InvoiceResponseReceivingNotificationRO);
            }
            else if(InvoiceResponseSendingNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.InvoiceResponseSendingNotificationRO>(null, InvoiceResponseSendingNotificationRO);
            }
            else if(InvoiceSendingNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.InvoiceSendingNotificationRO>(null, InvoiceSendingNotificationRO);
            }
            else if(IrasSendingNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.IrasSendingNotificationRO>(null, IrasSendingNotificationRO);
            }
            else if(LegalEntityCorppassC5NotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassC5NotificationRO>(null, LegalEntityCorppassC5NotificationRO);
            }
            else if(LegalEntityCorppassKycNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.LegalEntityCorppassKycNotificationRO>(null, LegalEntityCorppassKycNotificationRO);
            }
            else if(MLRReceivingNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.MLRReceivingNotificationRO>(null, MLRReceivingNotificationRO);
            }
            else if(OrderReceivingNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.OrderReceivingNotificationRO>(null, OrderReceivingNotificationRO);
            }
            else if(OrderSendingNotificationRO != null)
            {
                writer.WriteObjectValue<global::Peppol.Ademico.Kiota.Models.OrderSendingNotificationRO>(null, OrderSendingNotificationRO);
            }
        }
    }
}
#pragma warning restore CS0618
