// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>The status of the Order</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OrderStatusEnumRO
    {
        [EnumMember(Value = "QUEUED")]
        #pragma warning disable CS1591
        QUEUED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SENT")]
        #pragma warning disable CS1591
        SENT,
        #pragma warning restore CS1591
        [EnumMember(Value = "SEND_FAILED")]
        #pragma warning disable CS1591
        SEND_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TECHNICAL_ACCEPTANCE")]
        #pragma warning disable CS1591
        TECHNICAL_ACCEPTANCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        REJECTED,
        #pragma warning restore CS1591
    }
}
