// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>The supported documents the participant can receive.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PeppolDocumentSchemeEnumRO
    {
        [EnumMember(Value = "PEPPOL_BIS_BILLING_UBL_INVOICE_V3")]
        #pragma warning disable CS1591
        PEPPOL_BIS_BILLING_UBL_INVOICE_V3,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_BIS_BILLING_UBL_CREDIT_NOTE_V3")]
        #pragma warning disable CS1591
        PEPPOL_BIS_BILLING_UBL_CREDIT_NOTE_V3,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_BIS_SELF_BILLING_UBL_INVOICE_V3")]
        #pragma warning disable CS1591
        PEPPOL_BIS_SELF_BILLING_UBL_INVOICE_V3,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_BIS_SELF_BILLING_UBL_CREDIT_NOTE_V3")]
        #pragma warning disable CS1591
        PEPPOL_BIS_SELF_BILLING_UBL_CREDIT_NOTE_V3,
        #pragma warning restore CS1591
        [EnumMember(Value = "XRECHNUNG_UBL_INVOICE_V3_0")]
        #pragma warning disable CS1591
        XRECHNUNG_UBL_INVOICE_V3_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "XRECHNUNG_UBL_CREDIT_NOTE_V3_0")]
        #pragma warning disable CS1591
        XRECHNUNG_UBL_CREDIT_NOTE_V3_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "AU_NZ_UBL_INVOICE_V3")]
        #pragma warning disable CS1591
        AU_NZ_UBL_INVOICE_V3,
        #pragma warning restore CS1591
        [EnumMember(Value = "AU_NZ_UBL_CREDIT_NOTE_V3")]
        #pragma warning disable CS1591
        AU_NZ_UBL_CREDIT_NOTE_V3,
        #pragma warning restore CS1591
        [EnumMember(Value = "A_NZ_PINT_INVOICE_V1_0")]
        #pragma warning disable CS1591
        A_NZ_PINT_INVOICE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "A_NZ_PINT_CREDIT_NOTE_V1_0")]
        #pragma warning disable CS1591
        A_NZ_PINT_CREDIT_NOTE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "A_NZ_PINT_INVOICE_V1_0_WILDCARD")]
        #pragma warning disable CS1591
        A_NZ_PINT_INVOICE_V1_0_WILDCARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "A_NZ_PINT_CREDIT_NOTE_V1_0_WILDCARD")]
        #pragma warning disable CS1591
        A_NZ_PINT_CREDIT_NOTE_V1_0_WILDCARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "SG_PEPPOL_BIS_BILLING_3_0_INVOICE")]
        #pragma warning disable CS1591
        SG_PEPPOL_BIS_BILLING_3_0_INVOICE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SG_PEPPOL_BIS_BILLING_3_0_CREDIT_NOTE")]
        #pragma warning disable CS1591
        SG_PEPPOL_BIS_BILLING_3_0_CREDIT_NOTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SG_PINT_INVOICE_V1_0")]
        #pragma warning disable CS1591
        SG_PINT_INVOICE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "SG_PINT_CREDIT_NOTE_V1_0")]
        #pragma warning disable CS1591
        SG_PINT_CREDIT_NOTE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_SG_ORDER_BALANCE")]
        #pragma warning disable CS1591
        PEPPOL_SG_ORDER_BALANCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY_PINT_INVOICE_V1_0")]
        #pragma warning disable CS1591
        MY_PINT_INVOICE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY_PINT_INVOICE_V1_0_WILDCARD")]
        #pragma warning disable CS1591
        MY_PINT_INVOICE_V1_0_WILDCARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY_PINT_SELF_BILLING_INVOICE_V1_0")]
        #pragma warning disable CS1591
        MY_PINT_SELF_BILLING_INVOICE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY_PINT_SELF_BILLING_INVOICE_V1_0_WILDCARD")]
        #pragma warning disable CS1591
        MY_PINT_SELF_BILLING_INVOICE_V1_0_WILDCARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY_PINT_CREDIT_NOTE_V1_0")]
        #pragma warning disable CS1591
        MY_PINT_CREDIT_NOTE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY_PINT_CREDIT_NOTE_V1_0_WILDCARD")]
        #pragma warning disable CS1591
        MY_PINT_CREDIT_NOTE_V1_0_WILDCARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY_PINT_SELF_BILLING_CREDIT_NOTE_V1_0")]
        #pragma warning disable CS1591
        MY_PINT_SELF_BILLING_CREDIT_NOTE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "MY_PINT_SELF_BILLING_CREDIT_NOTE_V1_0_WILDCARD")]
        #pragma warning disable CS1591
        MY_PINT_SELF_BILLING_CREDIT_NOTE_V1_0_WILDCARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "SI_UBL_2_0_INVOICE")]
        #pragma warning disable CS1591
        SI_UBL_2_0_INVOICE,
        #pragma warning restore CS1591
        [EnumMember(Value = "SI_UBL_2_0_CREDITNOTE")]
        #pragma warning disable CS1591
        SI_UBL_2_0_CREDITNOTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "UBL_BE_INVOICE_3_0")]
        #pragma warning disable CS1591
        UBL_BE_INVOICE_3_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "UBL_BE_CREDIT_NOTE_3_0")]
        #pragma warning disable CS1591
        UBL_BE_CREDIT_NOTE_3_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_ORDER_TRANSACTION_3_0_ORDER_ONLY")]
        #pragma warning disable CS1591
        PEPPOL_ORDER_TRANSACTION_3_0_ORDER_ONLY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_ORDER_TRANSACTION_3_0_ADVANCED")]
        #pragma warning disable CS1591
        PEPPOL_ORDER_TRANSACTION_3_0_ADVANCED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_ORDER_CHANGE")]
        #pragma warning disable CS1591
        PEPPOL_ORDER_CHANGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_ORDER_CANCELLATION")]
        #pragma warning disable CS1591
        PEPPOL_ORDER_CANCELLATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_ORDER_RESPONSE_ADVANCED")]
        #pragma warning disable CS1591
        PEPPOL_ORDER_RESPONSE_ADVANCED,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_MESSAGE_LEVEL_RESPONSE_TRANSACTION_3_0")]
        #pragma warning disable CS1591
        PEPPOL_MESSAGE_LEVEL_RESPONSE_TRANSACTION_3_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_INVOICE_RESPONSE_TRANSACTION_3_0")]
        #pragma warning disable CS1591
        PEPPOL_INVOICE_RESPONSE_TRANSACTION_3_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "JP_PINT_INVOICE_V1_0")]
        #pragma warning disable CS1591
        JP_PINT_INVOICE_V1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "JP_PINT_INVOICE_V1_0_WILDCARD")]
        #pragma warning disable CS1591
        JP_PINT_INVOICE_V1_0_WILDCARD,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_PINT_INVOICE_1_0")]
        #pragma warning disable CS1591
        PEPPOL_PINT_INVOICE_1_0,
        #pragma warning restore CS1591
        [EnumMember(Value = "PEPPOL_PINT_CREDIT_NOTE_V1_0")]
        #pragma warning disable CS1591
        PEPPOL_PINT_CREDIT_NOTE_V1_0,
        #pragma warning restore CS1591
    }
}
