// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    /// <summary>The document type: Eg INVOICE, CREDIT_NOTE, ORDER</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PeppolDocumentTypeRO
    {
        [EnumMember(Value = "INVOICE")]
        #pragma warning disable CS1591
        INVOICE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREDIT_NOTE")]
        #pragma warning disable CS1591
        CREDIT_NOTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CII_INVOICE")]
        #pragma warning disable CS1591
        CII_INVOICE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORDER")]
        #pragma warning disable CS1591
        ORDER,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORDER_ADVANCED")]
        #pragma warning disable CS1591
        ORDER_ADVANCED,
        #pragma warning restore CS1591
        [EnumMember(Value = "SG_ORDER_BALANCE")]
        #pragma warning disable CS1591
        SG_ORDER_BALANCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORDER_CHANGE")]
        #pragma warning disable CS1591
        ORDER_CHANGE,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORDER_CANCELLATION")]
        #pragma warning disable CS1591
        ORDER_CANCELLATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "ORDER_RESPONSE_ADVANCED")]
        #pragma warning disable CS1591
        ORDER_RESPONSE_ADVANCED,
        #pragma warning restore CS1591
    }
}
