// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Peppol.Ademico.Kiota.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class XsdValidationReportRO : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The errorsCount property</summary>
        public int? ErrorsCount { get; set; }
        /// <summary>The reportStatus property</summary>
        public global::Peppol.Ademico.Kiota.Models.ValidationReportStatus? ReportStatus { get; set; }
        /// <summary>The validatedWith property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ValidatedWith { get; set; }
#nullable restore
#else
        public string ValidatedWith { get; set; }
#endif
        /// <summary>The validationType property</summary>
        public global::Peppol.Ademico.Kiota.Models.ValidationType? ValidationType { get; set; }
        /// <summary>The warningsCount property</summary>
        public int? WarningsCount { get; set; }
        /// <summary>The xsdValidationMessages property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Peppol.Ademico.Kiota.Models.XsdValidationMessageRO>? XsdValidationMessages { get; set; }
#nullable restore
#else
        public List<global::Peppol.Ademico.Kiota.Models.XsdValidationMessageRO> XsdValidationMessages { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Peppol.Ademico.Kiota.Models.XsdValidationReportRO"/> and sets the default values.
        /// </summary>
        public XsdValidationReportRO()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Peppol.Ademico.Kiota.Models.XsdValidationReportRO"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Peppol.Ademico.Kiota.Models.XsdValidationReportRO CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Peppol.Ademico.Kiota.Models.XsdValidationReportRO();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "errorsCount", n => { ErrorsCount = n.GetIntValue(); } },
                { "reportStatus", n => { ReportStatus = n.GetEnumValue<global::Peppol.Ademico.Kiota.Models.ValidationReportStatus>(); } },
                { "validatedWith", n => { ValidatedWith = n.GetStringValue(); } },
                { "validationType", n => { ValidationType = n.GetEnumValue<global::Peppol.Ademico.Kiota.Models.ValidationType>(); } },
                { "warningsCount", n => { WarningsCount = n.GetIntValue(); } },
                { "xsdValidationMessages", n => { XsdValidationMessages = n.GetCollectionOfObjectValues<global::Peppol.Ademico.Kiota.Models.XsdValidationMessageRO>(global::Peppol.Ademico.Kiota.Models.XsdValidationMessageRO.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("errorsCount", ErrorsCount);
            writer.WriteEnumValue<global::Peppol.Ademico.Kiota.Models.ValidationReportStatus>("reportStatus", ReportStatus);
            writer.WriteStringValue("validatedWith", ValidatedWith);
            writer.WriteEnumValue<global::Peppol.Ademico.Kiota.Models.ValidationType>("validationType", ValidationType);
            writer.WriteIntValue("warningsCount", WarningsCount);
            writer.WriteCollectionOfObjectValues<global::Peppol.Ademico.Kiota.Models.XsdValidationMessageRO>("xsdValidationMessages", XsdValidationMessages);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
